from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import List

from ..models import ExportRequest, Paper


def export_markdown(request: ExportRequest) -> str:
    lines = [
        "# " + request.title,
        "",
        f"> Generated by LatticeScholar at {datetime.now(timezone.utc).isoformat()}",
        "> AI-assisted content is a draft. Verify every citation, policy statement, and novelty claim.",
        "",
    ]
    if request.query:
        lines.extend(["## Research question / query", "", request.query, ""])
    if request.papers:
        lines.extend(["## Evidence set", ""])
        for index, paper in enumerate(request.papers, 1):
            metadata = ", ".join(x for x in [str(paper.year or ""), paper.venue] if x)
            link = "https://doi.org/" + paper.doi if paper.doi else paper.url
            lines.append(f"{index}. **{paper.title}** — {metadata}")
            if paper.authors:
                lines.append("   - Authors: " + ", ".join(paper.authors[:8]))
            if link:
                lines.append("   - Source: " + link)
            if paper.abstract:
                lines.append("   - Abstract: " + paper.abstract[:1000])
        lines.append("")
    if request.analyses:
        lines.extend(["## Paper analysis", ""])
        for analysis in request.analyses:
            lines.extend(
                [
                    "### Core problem",
                    analysis.core_problem,
                    "",
                    "**Innovations claimed/extracted**",
                    *["- " + item for item in analysis.innovations],
                    "",
                    "**Findings**",
                    *["- " + item for item in analysis.findings],
                    "",
                    "**Limitations**",
                    *["- " + item for item in analysis.limitations],
                    "",
                ]
            )
    if request.ideas:
        lines.extend(["## Candidate ideas (hypotheses, not established novelty)", ""])
        for idea in request.ideas:
            lines.extend(
                [
                    "### " + idea.title,
                    "",
                    "**Research question:** " + idea.research_question,
                    "",
                    "**Hypothesis:** " + idea.hypothesis,
                    "",
                    "**First validation**",
                    *["- " + item for item in idea.first_validation],
                    "",
                ]
            )
    if request.policies:
        lines.extend(["## Policy evidence", ""])
        for policy in request.policies:
            lines.append(
                f"- [{policy.title}]({policy.url}) — {policy.issuer}, {policy.published_at}"
            )
        lines.append("")
    lines.extend(
        [
            "## Verification checklist",
            "",
            "- [ ] DOI, authors, year, and version verified against the publisher or repository",
            "- [ ] Retractions, corrections, and expressions of concern checked",
            "- [ ] Journal scope, fees, indexing, and submission rules checked on the official site",
            "- [ ] Policy validity, jurisdiction, and original wording checked",
            "- [ ] Novelty checked with a documented, reproducible search strategy",
            "- [ ] Data rights, privacy, ethics review, and statistical power assessed",
            "",
        ]
    )
    return "\n".join(lines)


def _citation_key(paper: Paper, index: int) -> str:
    author = paper.authors[0].split()[-1] if paper.authors else "source"
    title_word = next(iter(re.findall(r"[A-Za-z0-9]+", paper.title)), "work")
    raw = f"{author}{paper.year or 'nd'}{title_word}"
    cleaned = re.sub(r"[^A-Za-z0-9_-]", "", raw)
    return cleaned[:60] or f"lattice{index}"


def export_bibtex(papers: List[Paper]) -> str:
    entries = []
    used = set()
    for index, paper in enumerate(papers, 1):
        base_key = _citation_key(paper, index)
        key = base_key
        suffix = 2
        while key.casefold() in used:
            key = f"{base_key}{suffix}"
            suffix += 1
        used.add(key.casefold())

        def safe(value: str) -> str:
            return value.replace("{", "\\{").replace("}", "\\}").replace("\n", " ")

        fields = [("title", paper.title)]
        if paper.authors:
            fields.append(("author", " and ".join(paper.authors)))
        if paper.year:
            fields.append(("year", str(paper.year)))
        if paper.venue:
            fields.append(("journal", paper.venue))
        if paper.doi:
            fields.append(("doi", paper.doi))
        if paper.url:
            fields.append(("url", paper.url))
        body = ",\n".join(f"  {name} = {{{safe(value)}}}" for name, value in fields)
        entries.append(f"@article{{{key},\n{body}\n}}")
    return "\n\n".join(entries) + "\n"


def export_ris(papers: List[Paper]) -> str:
    entries = []
    for paper in papers:
        lines = ["TY  - JOUR", f"TI  - {paper.title}"]
        lines.extend(f"AU  - {author}" for author in paper.authors)
        if paper.year:
            lines.append(f"PY  - {paper.year}")
        if paper.venue:
            lines.append(f"JO  - {paper.venue}")
        if paper.doi:
            lines.append(f"DO  - {paper.doi}")
        if paper.url:
            lines.append(f"UR  - {paper.url}")
        if paper.abstract:
            lines.append(f"AB  - {paper.abstract.replace(chr(10), ' ')}")
        lines.append("ER  -")
        entries.append("\n".join(lines))
    return "\n\n".join(entries) + "\n"
